Add initial implementation of ELO calculation
realpoke/genranks pull request #1
Opened 2023-06-20 19:15 UTC by ra-97

2023-06-20 21:10 UTC, realpoke requested changes
The flow is there, we can just optimize it and make it easier to read.

And we need a winner field on the `game` model for you to use!

2023-06-20 21:10 UTC, realpoke commented on app/Listeners/UpdateUserElo.php
> +        $game->UpdateUserElo($userA, $userB, 30, $hasAWon === $hasAWon);
I don't think we should have all these values out here. So remove them and don't have any arguments in the `UpdateUserElo` function, since the game already have the users and their elo.

2023-06-20 21:10 UTC, realpoke commented on app/Models/Game.php
> +    public function UpdateUserElo(User $userA, User $userB, int $eloFactor = 30, int $hasAWon = true)
Remove all arguments, since the game already have all this info.

2023-06-20 21:10 UTC, realpoke commented on app/Models/Game.php
> +        $userB->addElo($userBElo);
The winner gain elo, the loser should lose elo. Use the `removeElo` function on the user for the losing player.

2023-06-20 21:10 UTC, realpoke commented on app/Models/Game.php
> +        $userBElo = $userB->elo;
You can get the games users instead of the arguments `$this->users()`, and I think its a collection. So you can do foreach, first, last or whatever on it instead of indexing it like an array.

2023-06-20 21:10 UTC, realpoke commented on app/Models/Game.php
> +        if ($hasAWon) {
We should have new field on the `game` model that has the winner of the game.
This should be a one-to-many relationship, where a game can have one winner and a user can have many winning games.

Then for now when creating a game we just take one of the players and assign them as the winner until we find a way to get the real winner!

2023-06-21 06:42 UTC, ra-97 commented on app/Models/Game.php
> +        if ($hasAWon) {
@realpoke I think it should be just a plain one-to-one relationship 🤔 because as every game will have a collection of users, only one of those users is the winner, I mean for every unique game. If you then need to get all the games the player won, just filter by when the winner is that user I think.
What do u think?

2023-06-21 06:55 UTC, ra-97 commented on app/Models/Game.php
> +        if ($hasAWon) {
Or actually nvm, I think you are right.

2023-06-21 06:56 UTC, realpoke commented on app/Models/Game.php
> +        if ($hasAWon) {
It should not be a one-to-one relationship, since the user can win multiple games. If it's a one-to-one relation, then the user can only win one game ever.

But we just add a winner user ID to the game table.

2023-06-21 07:10 UTC, realpoke commented
The winner of a game can be null, so make sure you check that too. Since if its a tie or the game crashes.

2023-06-21 19:16 UTC, realpoke requested changes

2023-06-21 19:16 UTC, realpoke commented on app/Models/Game.php
> -
Don't remove the function, this is the winner relationship.

2023-06-21 19:16 UTC, realpoke commented on app/Models/Game.php
>          $winner = $this->winner();
The $winner here is a user.

2023-06-21 19:16 UTC, realpoke commented on app/Models/Game.php
> +        if ($winner->winner_id == $userA->id) {
Since both are user classes, you can just compare the whole class instead of getting the id's.

Also the $winner is a user which don't have the winner_id field, but just has the id field.

2023-06-21 19:29 UTC, closed without merging